name: Node.js Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Print SSH_PRIVATE_KEY
        run: echo "SSH_PRIVATE_KEY is ${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 159.65.255.38
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your private key as a secret in GitHub
          script: |
            cd Smash-Moment-Alpha/
            git pull origin main
            npm install
            # pm2 start -f server.js
        
